name: com_kamnopislam
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^7.0.2
  url_launcher: ^6.1.12
  webview_flutter: ^4.2.2
  animated_text_kit: ^4.2.2
  shared_preferences: ^2.2.0
  material_symbols_icons: ^4.2668.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/facebook.png
    - assets/icons/telegram.png
    - assets/icons/youtube.png
    - assets/images/logo.png

  fonts:
    - family: Battambang
      fonts:
        - asset: assets/fonts/battambang.ttf
    - family: Koulen
      fonts:
        - asset: assets/fonts/koulen.ttf
        
